Initialize nouroutine with multiple modules
metarhia/noroutine pull request #18
Opened 2021-11-04 21:00 UTC by Ranko95

- [x] tests and linter show no problems (`npm t`)
- [x] tests are added/updated for bug fixes and new features
- [x] code is properly formatted (`npm run fmt`)
- [x] description of changes is added in CHANGELOG.md
- [x] update .d.ts typings

2021-11-04 21:01 UTC, Ranko95 commented
@tshemsedinov

2021-11-04 21:59 UTC, tshemsedinov requested changes
Great work, just need a few fixes

2021-11-04 21:59 UTC, tshemsedinov commented on noroutine.js
> +  balancer.targets = options.modules.map((m) => findModule(m));
```suggestion
  balancer.targets = options.modules.map(findModule);
```

2021-11-04 21:59 UTC, tshemsedinov commented on lib/worker.js
> +const resolvedModules = workerData.modules.map((m) => require(m));
```suggestion
const resolvedModules = workerData.modules.map(require);
```

2021-11-04 21:59 UTC, tshemsedinov commented on lib/worker.js
> +const resolvedModules = workerData.modules.map((m) => require(m));
You can rewrite this with reduce in 1 line

2021-11-05 16:31 UTC, tshemsedinov commented on README.md
>    const res = await module1.method1('value');
```suggestion
  const res1 = await module1.method1('value1');
```

2021-11-05 16:32 UTC, tshemsedinov commented on README.md
> +  console.log({ res, res1 });
```suggestion
  const res2 = await module2.method2('value2');
  console.log({ res1, res2 });
```

2021-11-05 16:35 UTC, tshemsedinov commented on lib/worker.js
> +);
```suggestion
const names = workerData.modules;
const target = names.reduce((o, name) => ({ ...o, ...require(name) }), {});
```

2021-11-05 16:37 UTC, tshemsedinov commented
@Ranko95 see my commit, going to land this PR after that

2021-11-05 19:47 UTC, Ranko95 commented
@tshemsedinov , saw your commit, thanks for suggestions!

2021-11-08 00:41 UTC, tshemsedinov commented
Landed in https://github.com/metarhia/noroutine/commit/402f3ec14a3fa8aa69b6e04f30a66a15c4527e5f

2021-11-08 00:41 UTC, closed without merging